/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class AccCharge : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int stopId;
        private int rateType;
        private int contractId;
        private int accChargeId;
        private string description;
        private double charge;
        private double sellCharge;
        private double resellCharge;
        private double modifier;
        private int serviceLevel;
        private string updatedBy;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("StopId")]
        public int StopId 
        { 
            get 
            {
                return this.stopId; 
            } 
            set 
            {
                this.stopId = value;
                onPropertyChanged("StopId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RateType")]
        public int RateType 
        { 
            get 
            {
                return this.rateType; 
            } 
            set 
            {
                this.rateType = value;
                onPropertyChanged("RateType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ContractId")]
        public int ContractId 
        { 
            get 
            {
                return this.contractId; 
            } 
            set 
            {
                this.contractId = value;
                onPropertyChanged("ContractId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AccChargeId")]
        public int AccChargeId 
        { 
            get 
            {
                return this.accChargeId; 
            } 
            set 
            {
                this.accChargeId = value;
                onPropertyChanged("AccChargeId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Charge")]
        public double Charge 
        { 
            get 
            {
                return this.charge; 
            } 
            set 
            {
                this.charge = value;
                onPropertyChanged("Charge");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SellCharge")]
        public double SellCharge 
        { 
            get 
            {
                return this.sellCharge; 
            } 
            set 
            {
                this.sellCharge = value;
                onPropertyChanged("SellCharge");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ResellCharge")]
        public double ResellCharge 
        { 
            get 
            {
                return this.resellCharge; 
            } 
            set 
            {
                this.resellCharge = value;
                onPropertyChanged("ResellCharge");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Modifier")]
        public double Modifier 
        { 
            get 
            {
                return this.modifier; 
            } 
            set 
            {
                this.modifier = value;
                onPropertyChanged("Modifier");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ServiceLevel")]
        public int ServiceLevel 
        { 
            get 
            {
                return this.serviceLevel; 
            } 
            set 
            {
                this.serviceLevel = value;
                onPropertyChanged("ServiceLevel");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("UpdatedBy")]
        public string UpdatedBy 
        { 
            get 
            {
                return this.updatedBy; 
            } 
            set 
            {
                this.updatedBy = value;
                onPropertyChanged("UpdatedBy");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 