/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class ACCCHARGE : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int sTOPID;
        private int rATETYPE;
        private int cONTRACTID;
        private int aCCCHARGEID;
        private string dESCRIPTION;
        private double cHARGE;
        private double sELLCHARGE;
        private double rESELLCHARGE;
        private double mODIFIER;
        private int sERVICELEVEL;
        private string uPDATEDBY;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("STOP_ID")]
        public int STOPID 
        { 
            get 
            {
                return this.sTOPID; 
            } 
            set 
            {
                this.sTOPID = value;
                onPropertyChanged("STOPID");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RATE_TYPE")]
        public int RATETYPE 
        { 
            get 
            {
                return this.rATETYPE; 
            } 
            set 
            {
                this.rATETYPE = value;
                onPropertyChanged("RATETYPE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CONTRACT_ID")]
        public int CONTRACTID 
        { 
            get 
            {
                return this.cONTRACTID; 
            } 
            set 
            {
                this.cONTRACTID = value;
                onPropertyChanged("CONTRACTID");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ACC_CHARGE_ID")]
        public int ACCCHARGEID 
        { 
            get 
            {
                return this.aCCCHARGEID; 
            } 
            set 
            {
                this.aCCCHARGEID = value;
                onPropertyChanged("ACCCHARGEID");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("DESCRIPTION")]
        public string DESCRIPTION 
        { 
            get 
            {
                return this.dESCRIPTION; 
            } 
            set 
            {
                this.dESCRIPTION = value;
                onPropertyChanged("DESCRIPTION");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CHARGE")]
        public double CHARGE 
        { 
            get 
            {
                return this.cHARGE; 
            } 
            set 
            {
                this.cHARGE = value;
                onPropertyChanged("CHARGE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SELL_CHARGE")]
        public double SELLCHARGE 
        { 
            get 
            {
                return this.sELLCHARGE; 
            } 
            set 
            {
                this.sELLCHARGE = value;
                onPropertyChanged("SELLCHARGE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RESELL_CHARGE")]
        public double RESELLCHARGE 
        { 
            get 
            {
                return this.rESELLCHARGE; 
            } 
            set 
            {
                this.rESELLCHARGE = value;
                onPropertyChanged("RESELLCHARGE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("MODIFIER")]
        public double MODIFIER 
        { 
            get 
            {
                return this.mODIFIER; 
            } 
            set 
            {
                this.mODIFIER = value;
                onPropertyChanged("MODIFIER");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SERVICE_LEVEL")]
        public int SERVICELEVEL 
        { 
            get 
            {
                return this.sERVICELEVEL; 
            } 
            set 
            {
                this.sERVICELEVEL = value;
                onPropertyChanged("SERVICELEVEL");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("UPDATED_BY")]
        public string UPDATEDBY 
        { 
            get 
            {
                return this.uPDATEDBY; 
            } 
            set 
            {
                this.uPDATEDBY = value;
                onPropertyChanged("UPDATEDBY");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 