/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class ACCITEM : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int aCCCHARGEID;
        private string dESCRIPTION;
        private string lONGDESCRIPTION;
        private string aCCCODE;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ACC_CHARGE_ID")]
        public int ACCCHARGEID 
        { 
            get 
            {
                return this.aCCCHARGEID; 
            } 
            set 
            {
                this.aCCCHARGEID = value;
                onPropertyChanged("ACCCHARGEID");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("DESCRIPTION")]
        public string DESCRIPTION 
        { 
            get 
            {
                return this.dESCRIPTION; 
            } 
            set 
            {
                this.dESCRIPTION = value;
                onPropertyChanged("DESCRIPTION");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LONG_DESCRIPTION")]
        public string LONGDESCRIPTION 
        { 
            get 
            {
                return this.lONGDESCRIPTION; 
            } 
            set 
            {
                this.lONGDESCRIPTION = value;
                onPropertyChanged("LONGDESCRIPTION");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ACC_CODE")]
        public string ACCCODE 
        { 
            get 
            {
                return this.aCCCODE; 
            } 
            set 
            {
                this.aCCCODE = value;
                onPropertyChanged("ACCCODE");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 