/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class AccItem : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int accChargeId;
        private string description;
        private string longDescription;
        private string accCode;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AccChargeId")]
        public int AccChargeId 
        { 
            get 
            {
                return this.accChargeId; 
            } 
            set 
            {
                this.accChargeId = value;
                onPropertyChanged("AccChargeId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("LongDescription")]
        public string LongDescription 
        { 
            get 
            {
                return this.longDescription; 
            } 
            set 
            {
                this.longDescription = value;
                onPropertyChanged("LongDescription");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AccCode")]
        public string AccCode 
        { 
            get 
            {
                return this.accCode; 
            } 
            set 
            {
                this.accCode = value;
                onPropertyChanged("AccCode");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 