/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class ERROR : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int nUMBER = 1;
        private string dESCRIPTION;
        private int sEVERITY;

        /// <summary>
        /// Error Number
        /// </summary>
        [JsonProperty("NUMBER")]
        public int NUMBER 
        { 
            get 
            {
                return this.nUMBER; 
            } 
            set 
            {
                this.nUMBER = value;
                onPropertyChanged("NUMBER");
            }
        }

        /// <summary>
        /// Description of Error
        /// </summary>
        [JsonProperty("DESCRIPTION")]
        public string DESCRIPTION 
        { 
            get 
            {
                return this.dESCRIPTION; 
            } 
            set 
            {
                this.dESCRIPTION = value;
                onPropertyChanged("DESCRIPTION");
            }
        }

        /// <summary>
        /// Severity level of error
        /// </summary>
        [JsonProperty("SEVERITY")]
        public int SEVERITY 
        { 
            get 
            {
                return this.sEVERITY; 
            } 
            set 
            {
                this.sEVERITY = value;
                onPropertyChanged("SEVERITY");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 