/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class ORDER : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string oRDERID;
        private string uSERID;
        private DateTime rEADYDATE;
        private bool rATEORDER = false;
        private bool bOOKORDER = false;
        private SHIPMENTSTOPS sTOPS;
        private SHIPMENTPIECES pIECES;
        private ACCITEMS aCCITEMS;
        private SHIPMENTREFERENCES rEFERENCES;
        private ERRORS eRRORS;
        private int? oRDERUID;
        private string sPECIALINSTRUCTIONS;
        private string cOMMENTS;
        private DateTime? dATENEEDED;
        private string cARRIERSCAC;
        private string oRDERSTATUS;

        /// <summary>
        /// Id to import with order
        /// </summary>
        [JsonProperty("ORDER_ID")]
        public string ORDERID 
        { 
            get 
            {
                return this.oRDERID; 
            } 
            set 
            {
                this.oRDERID = value;
                onPropertyChanged("ORDERID");
            }
        }

        /// <summary>
        /// User to save order under
        /// </summary>
        [JsonProperty("USER_ID")]
        public string USERID 
        { 
            get 
            {
                return this.uSERID; 
            } 
            set 
            {
                this.uSERID = value;
                onPropertyChanged("USERID");
            }
        }

        /// <summary>
        /// Date order is ready for pickup
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("READY_DATE")]
        public DateTime READYDATE 
        { 
            get 
            {
                return this.rEADYDATE; 
            } 
            set 
            {
                this.rEADYDATE = value;
                onPropertyChanged("READYDATE");
            }
        }

        /// <summary>
        /// If you want to pre rate this pending order
        /// </summary>
        [JsonProperty("RATE_ORDER")]
        public bool RATEORDER 
        { 
            get 
            {
                return this.rATEORDER; 
            } 
            set 
            {
                this.rATEORDER = value;
                onPropertyChanged("RATEORDER");
            }
        }

        /// <summary>
        /// If you want to automatically book this order when submitted
        /// </summary>
        [JsonProperty("BOOK_ORDER")]
        public bool BOOKORDER 
        { 
            get 
            {
                return this.bOOKORDER; 
            } 
            set 
            {
                this.bOOKORDER = value;
                onPropertyChanged("BOOKORDER");
            }
        }

        /// <summary>
        /// Stops for order
        /// </summary>
        [JsonProperty("STOPS")]
        public SHIPMENTSTOPS STOPS 
        { 
            get 
            {
                return this.sTOPS; 
            } 
            set 
            {
                this.sTOPS = value;
                onPropertyChanged("STOPS");
            }
        }

        /// <summary>
        /// Pieces to include on order
        /// </summary>
        [JsonProperty("PIECES")]
        public SHIPMENTPIECES PIECES 
        { 
            get 
            {
                return this.pIECES; 
            } 
            set 
            {
                this.pIECES = value;
                onPropertyChanged("PIECES");
            }
        }

        /// <summary>
        /// Any Accessorials needed for order
        /// </summary>
        [JsonProperty("ACC_ITEMS")]
        public ACCITEMS ACCITEMS 
        { 
            get 
            {
                return this.aCCITEMS; 
            } 
            set 
            {
                this.aCCITEMS = value;
                onPropertyChanged("ACCITEMS");
            }
        }

        /// <summary>
        /// Any References for the Order
        /// </summary>
        [JsonProperty("REFERENCES")]
        public SHIPMENTREFERENCES REFERENCES 
        { 
            get 
            {
                return this.rEFERENCES; 
            } 
            set 
            {
                this.rEFERENCES = value;
                onPropertyChanged("REFERENCES");
            }
        }

        /// <summary>
        /// Any errors in processing
        /// </summary>
        [JsonProperty("ERRORS")]
        public ERRORS ERRORS 
        { 
            get 
            {
                return this.eRRORS; 
            } 
            set 
            {
                this.eRRORS = value;
                onPropertyChanged("ERRORS");
            }
        }

        /// <summary>
        /// Unique Id of Order
        /// </summary>
        [JsonProperty("ORDER_UID")]
        public int? ORDERUID 
        { 
            get 
            {
                return this.oRDERUID; 
            } 
            set 
            {
                this.oRDERUID = value;
                onPropertyChanged("ORDERUID");
            }
        }

        /// <summary>
        /// Any Special Instructions for order
        /// </summary>
        [JsonProperty("SPECIAL_INSTRUCTIONS")]
        public string SPECIALINSTRUCTIONS 
        { 
            get 
            {
                return this.sPECIALINSTRUCTIONS; 
            } 
            set 
            {
                this.sPECIALINSTRUCTIONS = value;
                onPropertyChanged("SPECIALINSTRUCTIONS");
            }
        }

        /// <summary>
        /// Any Comments about order
        /// </summary>
        [JsonProperty("COMMENTS")]
        public string COMMENTS 
        { 
            get 
            {
                return this.cOMMENTS; 
            } 
            set 
            {
                this.cOMMENTS = value;
                onPropertyChanged("COMMENTS");
            }
        }

        /// <summary>
        /// Date Order is needed by
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("DATE_NEEDED")]
        public DateTime? DATENEEDED 
        { 
            get 
            {
                return this.dATENEEDED; 
            } 
            set 
            {
                this.dATENEEDED = value;
                onPropertyChanged("DATENEEDED");
            }
        }

        /// <summary>
        /// SCAC of carrier to use if you want to book the order with a particular carrier
        /// </summary>
        [JsonProperty("CARRIER_SCAC")]
        public string CARRIERSCAC 
        { 
            get 
            {
                return this.cARRIERSCAC; 
            } 
            set 
            {
                this.cARRIERSCAC = value;
                onPropertyChanged("CARRIERSCAC");
            }
        }

        /// <summary>
        /// Status of the order
        /// </summary>
        [JsonProperty("ORDER_STATUS")]
        public string ORDERSTATUS 
        { 
            get 
            {
                return this.oRDERSTATUS; 
            } 
            set 
            {
                this.oRDERSTATUS = value;
                onPropertyChanged("ORDERSTATUS");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 