/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class Order : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string orderId;
        private string userId;
        private DateTime readyDate;
        private bool rateOrder = false;
        private bool bookOrder = false;
        private ShipmentStops stops;
        private ShipmentPieces pieces;
        private AccItems accItems;
        private ShipmentReferences references;
        private Errors errors;
        private int? orderUid;
        private string specialInstructions;
        private string comments;
        private DateTime? dateNeeded;
        private string carrierScac;
        private string orderStatus;

        /// <summary>
        /// Id to import with order
        /// </summary>
        [JsonProperty("OrderId")]
        public string OrderId 
        { 
            get 
            {
                return this.orderId; 
            } 
            set 
            {
                this.orderId = value;
                onPropertyChanged("OrderId");
            }
        }

        /// <summary>
        /// User to save order under
        /// </summary>
        [JsonProperty("UserId")]
        public string UserId 
        { 
            get 
            {
                return this.userId; 
            } 
            set 
            {
                this.userId = value;
                onPropertyChanged("UserId");
            }
        }

        /// <summary>
        /// Date order is ready for pickup
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("ReadyDate")]
        public DateTime ReadyDate 
        { 
            get 
            {
                return this.readyDate; 
            } 
            set 
            {
                this.readyDate = value;
                onPropertyChanged("ReadyDate");
            }
        }

        /// <summary>
        /// If you want to pre rate this pending order
        /// </summary>
        [JsonProperty("RateOrder")]
        public bool RateOrder 
        { 
            get 
            {
                return this.rateOrder; 
            } 
            set 
            {
                this.rateOrder = value;
                onPropertyChanged("RateOrder");
            }
        }

        /// <summary>
        /// If you want to automatically book this order when submitted
        /// </summary>
        [JsonProperty("BookOrder")]
        public bool BookOrder 
        { 
            get 
            {
                return this.bookOrder; 
            } 
            set 
            {
                this.bookOrder = value;
                onPropertyChanged("BookOrder");
            }
        }

        /// <summary>
        /// Stops for order
        /// </summary>
        [JsonProperty("Stops")]
        public ShipmentStops Stops 
        { 
            get 
            {
                return this.stops; 
            } 
            set 
            {
                this.stops = value;
                onPropertyChanged("Stops");
            }
        }

        /// <summary>
        /// Pieces to include on order
        /// </summary>
        [JsonProperty("Pieces")]
        public ShipmentPieces Pieces 
        { 
            get 
            {
                return this.pieces; 
            } 
            set 
            {
                this.pieces = value;
                onPropertyChanged("Pieces");
            }
        }

        /// <summary>
        /// Any Accessorials needed for order
        /// </summary>
        [JsonProperty("AccItems")]
        public AccItems AccItems 
        { 
            get 
            {
                return this.accItems; 
            } 
            set 
            {
                this.accItems = value;
                onPropertyChanged("AccItems");
            }
        }

        /// <summary>
        /// Any References for the Order
        /// </summary>
        [JsonProperty("References")]
        public ShipmentReferences References 
        { 
            get 
            {
                return this.references; 
            } 
            set 
            {
                this.references = value;
                onPropertyChanged("References");
            }
        }

        /// <summary>
        /// Any errors in processing
        /// </summary>
        [JsonProperty("Errors")]
        public Errors Errors 
        { 
            get 
            {
                return this.errors; 
            } 
            set 
            {
                this.errors = value;
                onPropertyChanged("Errors");
            }
        }

        /// <summary>
        /// Unique Id of Order
        /// </summary>
        [JsonProperty("OrderUid")]
        public int? OrderUid 
        { 
            get 
            {
                return this.orderUid; 
            } 
            set 
            {
                this.orderUid = value;
                onPropertyChanged("OrderUid");
            }
        }

        /// <summary>
        /// Any Special Instructions for order
        /// </summary>
        [JsonProperty("SpecialInstructions")]
        public string SpecialInstructions 
        { 
            get 
            {
                return this.specialInstructions; 
            } 
            set 
            {
                this.specialInstructions = value;
                onPropertyChanged("SpecialInstructions");
            }
        }

        /// <summary>
        /// Any Comments about order
        /// </summary>
        [JsonProperty("Comments")]
        public string Comments 
        { 
            get 
            {
                return this.comments; 
            } 
            set 
            {
                this.comments = value;
                onPropertyChanged("Comments");
            }
        }

        /// <summary>
        /// Date Order is needed by
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("DateNeeded")]
        public DateTime? DateNeeded 
        { 
            get 
            {
                return this.dateNeeded; 
            } 
            set 
            {
                this.dateNeeded = value;
                onPropertyChanged("DateNeeded");
            }
        }

        /// <summary>
        /// SCAC of carrier to use if you want to book the order with a particular carrier
        /// </summary>
        [JsonProperty("CarrierScac")]
        public string CarrierScac 
        { 
            get 
            {
                return this.carrierScac; 
            } 
            set 
            {
                this.carrierScac = value;
                onPropertyChanged("CarrierScac");
            }
        }

        /// <summary>
        /// Status of the order
        /// </summary>
        [JsonProperty("OrderStatus")]
        public string OrderStatus 
        { 
            get 
            {
                return this.orderStatus; 
            } 
            set 
            {
                this.orderStatus = value;
                onPropertyChanged("OrderStatus");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 