/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class QUOTE : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string uSERID;
        private string oRIGPOSTALCODE;
        private string dESTPOSTALCODE;
        private int sERVICETYPE = 0;
        private int cHARGETYPE = 0;
        private DateTime qUOTEDATE;
        private SHIPMENTPIECES pIECES;
        private ERRORS eRRORS;
        private string sYSTEMUSERID;
        private List<RATE> rATES;

        /// <summary>
        /// User for the quote
        /// </summary>
        [JsonProperty("USER_ID")]
        public string USERID 
        { 
            get 
            {
                return this.uSERID; 
            } 
            set 
            {
                this.uSERID = value;
                onPropertyChanged("USERID");
            }
        }

        /// <summary>
        /// Origin Postal Code
        /// </summary>
        [JsonProperty("ORIG_POSTAL_CODE")]
        public string ORIGPOSTALCODE 
        { 
            get 
            {
                return this.oRIGPOSTALCODE; 
            } 
            set 
            {
                this.oRIGPOSTALCODE = value;
                onPropertyChanged("ORIGPOSTALCODE");
            }
        }

        /// <summary>
        /// Destination Postal Code
        /// </summary>
        [JsonProperty("DEST_POSTAL_CODE")]
        public string DESTPOSTALCODE 
        { 
            get 
            {
                return this.dESTPOSTALCODE; 
            } 
            set 
            {
                this.dESTPOSTALCODE = value;
                onPropertyChanged("DESTPOSTALCODE");
            }
        }

        /// <summary>
        /// Service Type For Quote
        /// </summary>
        [JsonProperty("SERVICE_TYPE")]
        public int SERVICETYPE 
        { 
            get 
            {
                return this.sERVICETYPE; 
            } 
            set 
            {
                this.sERVICETYPE = value;
                onPropertyChanged("SERVICETYPE");
            }
        }

        /// <summary>
        /// Charge Type For Quote
        /// </summary>
        [JsonProperty("CHARGE_TYPE")]
        public int CHARGETYPE 
        { 
            get 
            {
                return this.cHARGETYPE; 
            } 
            set 
            {
                this.cHARGETYPE = value;
                onPropertyChanged("CHARGETYPE");
            }
        }

        /// <summary>
        /// Date quote is for
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("QUOTE_DATE")]
        public DateTime QUOTEDATE 
        { 
            get 
            {
                return this.qUOTEDATE; 
            } 
            set 
            {
                this.qUOTEDATE = value;
                onPropertyChanged("QUOTEDATE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PIECES")]
        public SHIPMENTPIECES PIECES 
        { 
            get 
            {
                return this.pIECES; 
            } 
            set 
            {
                this.pIECES = value;
                onPropertyChanged("PIECES");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ERRORS")]
        public ERRORS ERRORS 
        { 
            get 
            {
                return this.eRRORS; 
            } 
            set 
            {
                this.eRRORS = value;
                onPropertyChanged("ERRORS");
            }
        }

        /// <summary>
        /// Admin user requesting quote
        /// </summary>
        [JsonProperty("SYSTEM_USER_ID")]
        public string SYSTEMUSERID 
        { 
            get 
            {
                return this.sYSTEMUSERID; 
            } 
            set 
            {
                this.sYSTEMUSERID = value;
                onPropertyChanged("SYSTEMUSERID");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("RATES")]
        public List<RATE> RATES 
        { 
            get 
            {
                return this.rATES; 
            } 
            set 
            {
                this.rATES = value;
                onPropertyChanged("RATES");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 