/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class Quote : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string userId;
        private string origPostalCode;
        private string destPostalCode;
        private int serviceType = 0;
        private int chargeType = 0;
        private DateTime quoteDate;
        private ShipmentPieces pieces;
        private Errors errors;
        private string systemUserId;
        private List<Rate> rates;

        /// <summary>
        /// User for the quote
        /// </summary>
        [JsonProperty("UserId")]
        public string UserId 
        { 
            get 
            {
                return this.userId; 
            } 
            set 
            {
                this.userId = value;
                onPropertyChanged("UserId");
            }
        }

        /// <summary>
        /// Origin Postal Code
        /// </summary>
        [JsonProperty("OrigPostalCode")]
        public string OrigPostalCode 
        { 
            get 
            {
                return this.origPostalCode; 
            } 
            set 
            {
                this.origPostalCode = value;
                onPropertyChanged("OrigPostalCode");
            }
        }

        /// <summary>
        /// Destination Postal Code
        /// </summary>
        [JsonProperty("DestPostalCode")]
        public string DestPostalCode 
        { 
            get 
            {
                return this.destPostalCode; 
            } 
            set 
            {
                this.destPostalCode = value;
                onPropertyChanged("DestPostalCode");
            }
        }

        /// <summary>
        /// Service Type For Quote
        /// </summary>
        [JsonProperty("ServiceType")]
        public int ServiceType 
        { 
            get 
            {
                return this.serviceType; 
            } 
            set 
            {
                this.serviceType = value;
                onPropertyChanged("ServiceType");
            }
        }

        /// <summary>
        /// Charge Type For Quote
        /// </summary>
        [JsonProperty("ChargeType")]
        public int ChargeType 
        { 
            get 
            {
                return this.chargeType; 
            } 
            set 
            {
                this.chargeType = value;
                onPropertyChanged("ChargeType");
            }
        }

        /// <summary>
        /// Date quote is for
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("QuoteDate")]
        public DateTime QuoteDate 
        { 
            get 
            {
                return this.quoteDate; 
            } 
            set 
            {
                this.quoteDate = value;
                onPropertyChanged("QuoteDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Pieces")]
        public ShipmentPieces Pieces 
        { 
            get 
            {
                return this.pieces; 
            } 
            set 
            {
                this.pieces = value;
                onPropertyChanged("Pieces");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Errors")]
        public Errors Errors 
        { 
            get 
            {
                return this.errors; 
            } 
            set 
            {
                this.errors = value;
                onPropertyChanged("Errors");
            }
        }

        /// <summary>
        /// Admin user requesting quote
        /// </summary>
        [JsonProperty("SystemUserId")]
        public string SystemUserId 
        { 
            get 
            {
                return this.systemUserId; 
            } 
            set 
            {
                this.systemUserId = value;
                onPropertyChanged("SystemUserId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Rates")]
        public List<Rate> Rates 
        { 
            get 
            {
                return this.rates; 
            } 
            set 
            {
                this.rates = value;
                onPropertyChanged("Rates");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 