/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class RATE : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private bool mdefault = false;
        private string qUOTEID;
        private string cARRIERID;
        private string sCAC;
        private string cARRIERNAME;
        private int cONTRACTID;
        private string dESCRIPTION;
        private int sERVICEDAYS;
        private double bASERATE;
        private double fUELSURCHARGE;
        private double oTHERACC;
        private double tOTALRATE;
        private double sELLBASERATE;
        private double sELLFUELSURCHARGE;
        private double sELLOTHERACC;
        private double sELLTOTALRATE;
        private ACCITEMS aCCITEMS;

        /// <summary>
        /// If this is the selected rate
        /// </summary>
        [JsonProperty("default")]
        public bool Default 
        { 
            get 
            {
                return this.mdefault; 
            } 
            set 
            {
                this.mdefault = value;
                onPropertyChanged("Default");
            }
        }

        /// <summary>
        /// Quote Id
        /// </summary>
        [JsonProperty("QUOTE_ID")]
        public string QUOTEID 
        { 
            get 
            {
                return this.qUOTEID; 
            } 
            set 
            {
                this.qUOTEID = value;
                onPropertyChanged("QUOTEID");
            }
        }

        /// <summary>
        /// ID of the Carrier
        /// </summary>
        [JsonProperty("CARRIER_ID")]
        public string CARRIERID 
        { 
            get 
            {
                return this.cARRIERID; 
            } 
            set 
            {
                this.cARRIERID = value;
                onPropertyChanged("CARRIERID");
            }
        }

        /// <summary>
        /// SCAC of the Carrier
        /// </summary>
        [JsonProperty("SCAC")]
        public string SCAC 
        { 
            get 
            {
                return this.sCAC; 
            } 
            set 
            {
                this.sCAC = value;
                onPropertyChanged("SCAC");
            }
        }

        /// <summary>
        /// Name of the Carrier
        /// </summary>
        [JsonProperty("CARRIER_NAME")]
        public string CARRIERNAME 
        { 
            get 
            {
                return this.cARRIERNAME; 
            } 
            set 
            {
                this.cARRIERNAME = value;
                onPropertyChanged("CARRIERNAME");
            }
        }

        /// <summary>
        /// Id of contract used
        /// </summary>
        [JsonProperty("CONTRACT_ID")]
        public int CONTRACTID 
        { 
            get 
            {
                return this.cONTRACTID; 
            } 
            set 
            {
                this.cONTRACTID = value;
                onPropertyChanged("CONTRACTID");
            }
        }

        /// <summary>
        /// Description of contract used
        /// </summary>
        [JsonProperty("DESCRIPTION")]
        public string DESCRIPTION 
        { 
            get 
            {
                return this.dESCRIPTION; 
            } 
            set 
            {
                this.dESCRIPTION = value;
                onPropertyChanged("DESCRIPTION");
            }
        }

        /// <summary>
        /// Number of days to deliver item
        /// </summary>
        [JsonProperty("SERVICE_DAYS")]
        public int SERVICEDAYS 
        { 
            get 
            {
                return this.sERVICEDAYS; 
            } 
            set 
            {
                this.sERVICEDAYS = value;
                onPropertyChanged("SERVICEDAYS");
            }
        }

        /// <summary>
        /// Base Charge amount
        /// </summary>
        [JsonProperty("BASE_RATE")]
        public double BASERATE 
        { 
            get 
            {
                return this.bASERATE; 
            } 
            set 
            {
                this.bASERATE = value;
                onPropertyChanged("BASERATE");
            }
        }

        /// <summary>
        /// Fuel Surcharge amount
        /// </summary>
        [JsonProperty("FUEL_SURCHARGE")]
        public double FUELSURCHARGE 
        { 
            get 
            {
                return this.fUELSURCHARGE; 
            } 
            set 
            {
                this.fUELSURCHARGE = value;
                onPropertyChanged("FUELSURCHARGE");
            }
        }

        /// <summary>
        /// Total of Acc charges other than Base and Fuel
        /// </summary>
        [JsonProperty("OTHER_ACC")]
        public double OTHERACC 
        { 
            get 
            {
                return this.oTHERACC; 
            } 
            set 
            {
                this.oTHERACC = value;
                onPropertyChanged("OTHERACC");
            }
        }

        /// <summary>
        /// Total Rate
        /// </summary>
        [JsonProperty("TOTAL_RATE")]
        public double TOTALRATE 
        { 
            get 
            {
                return this.tOTALRATE; 
            } 
            set 
            {
                this.tOTALRATE = value;
                onPropertyChanged("TOTALRATE");
            }
        }

        /// <summary>
        /// Base Charge with markup applied
        /// </summary>
        [JsonProperty("SELL_BASE_RATE")]
        public double SELLBASERATE 
        { 
            get 
            {
                return this.sELLBASERATE; 
            } 
            set 
            {
                this.sELLBASERATE = value;
                onPropertyChanged("SELLBASERATE");
            }
        }

        /// <summary>
        /// Fuel Surcharge with markup applied
        /// </summary>
        [JsonProperty("SELL_FUEL_SURCHARGE")]
        public double SELLFUELSURCHARGE 
        { 
            get 
            {
                return this.sELLFUELSURCHARGE; 
            } 
            set 
            {
                this.sELLFUELSURCHARGE = value;
                onPropertyChanged("SELLFUELSURCHARGE");
            }
        }

        /// <summary>
        /// Total of Acc charges other than Base and Fuel with markup applied
        /// </summary>
        [JsonProperty("SELL_OTHER_ACC")]
        public double SELLOTHERACC 
        { 
            get 
            {
                return this.sELLOTHERACC; 
            } 
            set 
            {
                this.sELLOTHERACC = value;
                onPropertyChanged("SELLOTHERACC");
            }
        }

        /// <summary>
        /// Total Rate with markup applied
        /// </summary>
        [JsonProperty("SELL_TOTAL_RATE")]
        public double SELLTOTALRATE 
        { 
            get 
            {
                return this.sELLTOTALRATE; 
            } 
            set 
            {
                this.sELLTOTALRATE = value;
                onPropertyChanged("SELLTOTALRATE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ACC_ITEMS")]
        public ACCITEMS ACCITEMS 
        { 
            get 
            {
                return this.aCCITEMS; 
            } 
            set 
            {
                this.aCCITEMS = value;
                onPropertyChanged("ACCITEMS");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 