/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class Rate : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private bool mdefault = false;
        private string quoteId;
        private string carrierId;
        private string scac;
        private string carrierName;
        private int contractId;
        private string description;
        private int serviceDays;
        private double baseRate;
        private double fuelSurcharge;
        private double otherAcc;
        private double totalRate;
        private double sellBaseRate;
        private double sellFuelSurcharge;
        private double sellOtherAcc;
        private double sellTotalRate;
        private AccItems accitems;

        /// <summary>
        /// If this is the selected rate
        /// </summary>
        [JsonProperty("Default")]
        public bool Default 
        { 
            get 
            {
                return this.mdefault; 
            } 
            set 
            {
                this.mdefault = value;
                onPropertyChanged("Default");
            }
        }

        /// <summary>
        /// Quote Id
        /// </summary>
        [JsonProperty("QuoteId")]
        public string QuoteId 
        { 
            get 
            {
                return this.quoteId; 
            } 
            set 
            {
                this.quoteId = value;
                onPropertyChanged("QuoteId");
            }
        }

        /// <summary>
        /// ID of the Carrier
        /// </summary>
        [JsonProperty("CarrierId")]
        public string CarrierId 
        { 
            get 
            {
                return this.carrierId; 
            } 
            set 
            {
                this.carrierId = value;
                onPropertyChanged("CarrierId");
            }
        }

        /// <summary>
        /// SCAC of the Carrier
        /// </summary>
        [JsonProperty("Scac")]
        public string Scac 
        { 
            get 
            {
                return this.scac; 
            } 
            set 
            {
                this.scac = value;
                onPropertyChanged("Scac");
            }
        }

        /// <summary>
        /// Name of the Carrier
        /// </summary>
        [JsonProperty("CarrierName")]
        public string CarrierName 
        { 
            get 
            {
                return this.carrierName; 
            } 
            set 
            {
                this.carrierName = value;
                onPropertyChanged("CarrierName");
            }
        }

        /// <summary>
        /// Id of contract used
        /// </summary>
        [JsonProperty("ContractId")]
        public int ContractId 
        { 
            get 
            {
                return this.contractId; 
            } 
            set 
            {
                this.contractId = value;
                onPropertyChanged("ContractId");
            }
        }

        /// <summary>
        /// Description of contract used
        /// </summary>
        [JsonProperty("Description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// Number of days to deliver item
        /// </summary>
        [JsonProperty("ServiceDays")]
        public int ServiceDays 
        { 
            get 
            {
                return this.serviceDays; 
            } 
            set 
            {
                this.serviceDays = value;
                onPropertyChanged("ServiceDays");
            }
        }

        /// <summary>
        /// Base Charge amount
        /// </summary>
        [JsonProperty("BaseRate")]
        public double BaseRate 
        { 
            get 
            {
                return this.baseRate; 
            } 
            set 
            {
                this.baseRate = value;
                onPropertyChanged("BaseRate");
            }
        }

        /// <summary>
        /// Fuel Surcharge amount
        /// </summary>
        [JsonProperty("FuelSurcharge")]
        public double FuelSurcharge 
        { 
            get 
            {
                return this.fuelSurcharge; 
            } 
            set 
            {
                this.fuelSurcharge = value;
                onPropertyChanged("FuelSurcharge");
            }
        }

        /// <summary>
        /// Total of Acc charges other than Base and Fuel
        /// </summary>
        [JsonProperty("OtherAcc")]
        public double OtherAcc 
        { 
            get 
            {
                return this.otherAcc; 
            } 
            set 
            {
                this.otherAcc = value;
                onPropertyChanged("OtherAcc");
            }
        }

        /// <summary>
        /// Total Rate
        /// </summary>
        [JsonProperty("TotalRate")]
        public double TotalRate 
        { 
            get 
            {
                return this.totalRate; 
            } 
            set 
            {
                this.totalRate = value;
                onPropertyChanged("TotalRate");
            }
        }

        /// <summary>
        /// Base Charge with markup applied
        /// </summary>
        [JsonProperty("SellBaseRate")]
        public double SellBaseRate 
        { 
            get 
            {
                return this.sellBaseRate; 
            } 
            set 
            {
                this.sellBaseRate = value;
                onPropertyChanged("SellBaseRate");
            }
        }

        /// <summary>
        /// Fuel Surcharge with markup applied
        /// </summary>
        [JsonProperty("SellFuelSurcharge")]
        public double SellFuelSurcharge 
        { 
            get 
            {
                return this.sellFuelSurcharge; 
            } 
            set 
            {
                this.sellFuelSurcharge = value;
                onPropertyChanged("SellFuelSurcharge");
            }
        }

        /// <summary>
        /// Total of Acc charges other than Base and Fuel with markup applied
        /// </summary>
        [JsonProperty("SellOtherAcc")]
        public double SellOtherAcc 
        { 
            get 
            {
                return this.sellOtherAcc; 
            } 
            set 
            {
                this.sellOtherAcc = value;
                onPropertyChanged("SellOtherAcc");
            }
        }

        /// <summary>
        /// Total Rate with markup applied
        /// </summary>
        [JsonProperty("SellTotalRate")]
        public double SellTotalRate 
        { 
            get 
            {
                return this.sellTotalRate; 
            } 
            set 
            {
                this.sellTotalRate = value;
                onPropertyChanged("SellTotalRate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Accitems")]
        public AccItems Accitems 
        { 
            get 
            {
                return this.accitems; 
            } 
            set 
            {
                this.accitems = value;
                onPropertyChanged("Accitems");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 