/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class ShipmentPiece : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int units;
        private string containerId;
        private string containerDesc;
        private string description;
        private int weight;
        private bool isHazmat = false;
        private string classNumber;
        private string opsClass;
        private double? totalCube;
        private string packageContainerId;
        private string packageContainerDesc;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Units")]
        public int Units 
        { 
            get 
            {
                return this.units; 
            } 
            set 
            {
                this.units = value;
                onPropertyChanged("Units");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ContainerId")]
        public string ContainerId 
        { 
            get 
            {
                return this.containerId; 
            } 
            set 
            {
                this.containerId = value;
                onPropertyChanged("ContainerId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ContainerDesc")]
        public string ContainerDesc 
        { 
            get 
            {
                return this.containerDesc; 
            } 
            set 
            {
                this.containerDesc = value;
                onPropertyChanged("ContainerDesc");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Description")]
        public string Description 
        { 
            get 
            {
                return this.description; 
            } 
            set 
            {
                this.description = value;
                onPropertyChanged("Description");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Weight")]
        public int Weight 
        { 
            get 
            {
                return this.weight; 
            } 
            set 
            {
                this.weight = value;
                onPropertyChanged("Weight");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsHazmat")]
        public bool IsHazmat 
        { 
            get 
            {
                return this.isHazmat; 
            } 
            set 
            {
                this.isHazmat = value;
                onPropertyChanged("IsHazmat");
            }
        }

        /// <summary>
        /// Hazmat Class
        /// </summary>
        [JsonProperty("ClassNumber")]
        public string ClassNumber 
        { 
            get 
            {
                return this.classNumber; 
            } 
            set 
            {
                this.classNumber = value;
                onPropertyChanged("ClassNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OpsClass")]
        public string OpsClass 
        { 
            get 
            {
                return this.opsClass; 
            } 
            set 
            {
                this.opsClass = value;
                onPropertyChanged("OpsClass");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TotalCube")]
        public double? TotalCube 
        { 
            get 
            {
                return this.totalCube; 
            } 
            set 
            {
                this.totalCube = value;
                onPropertyChanged("TotalCube");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PackageContainerId")]
        public string PackageContainerId 
        { 
            get 
            {
                return this.packageContainerId; 
            } 
            set 
            {
                this.packageContainerId = value;
                onPropertyChanged("PackageContainerId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PackageContainerDesc")]
        public string PackageContainerDesc 
        { 
            get 
            {
                return this.packageContainerDesc; 
            } 
            set 
            {
                this.packageContainerDesc = value;
                onPropertyChanged("PackageContainerDesc");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 