/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class SHIPMENTPIECE : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int uNITS;
        private string cONTAINERID;
        private string cONTAINERDESC;
        private string dESCRIPTION;
        private int wEIGHT;
        private bool iSHAZMAT = false;
        private string cLASSNUMBER;
        private string oPSCLASS;
        private int? tOTALCUBE;
        private string pACKAGECONTAINERID;
        private string pACKAGECONTAINERDESC;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("UNITS")]
        public int UNITS 
        { 
            get 
            {
                return this.uNITS; 
            } 
            set 
            {
                this.uNITS = value;
                onPropertyChanged("UNITS");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CONTAINER_ID")]
        public string CONTAINERID 
        { 
            get 
            {
                return this.cONTAINERID; 
            } 
            set 
            {
                this.cONTAINERID = value;
                onPropertyChanged("CONTAINERID");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CONTAINER_DESC")]
        public string CONTAINERDESC 
        { 
            get 
            {
                return this.cONTAINERDESC; 
            } 
            set 
            {
                this.cONTAINERDESC = value;
                onPropertyChanged("CONTAINERDESC");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("DESCRIPTION")]
        public string DESCRIPTION 
        { 
            get 
            {
                return this.dESCRIPTION; 
            } 
            set 
            {
                this.dESCRIPTION = value;
                onPropertyChanged("DESCRIPTION");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("WEIGHT")]
        public int WEIGHT 
        { 
            get 
            {
                return this.wEIGHT; 
            } 
            set 
            {
                this.wEIGHT = value;
                onPropertyChanged("WEIGHT");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IS_HAZMAT")]
        public bool ISHAZMAT 
        { 
            get 
            {
                return this.iSHAZMAT; 
            } 
            set 
            {
                this.iSHAZMAT = value;
                onPropertyChanged("ISHAZMAT");
            }
        }

        /// <summary>
        /// Hazmat Class
        /// </summary>
        [JsonProperty("CLASS_NUMBER")]
        public string CLASSNUMBER 
        { 
            get 
            {
                return this.cLASSNUMBER; 
            } 
            set 
            {
                this.cLASSNUMBER = value;
                onPropertyChanged("CLASSNUMBER");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("OPS_CLASS")]
        public string OPSCLASS 
        { 
            get 
            {
                return this.oPSCLASS; 
            } 
            set 
            {
                this.oPSCLASS = value;
                onPropertyChanged("OPSCLASS");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TOTAL_CUBE")]
        public int? TOTALCUBE 
        { 
            get 
            {
                return this.tOTALCUBE; 
            } 
            set 
            {
                this.tOTALCUBE = value;
                onPropertyChanged("TOTALCUBE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PACKAGE_CONTAINER_ID")]
        public string PACKAGECONTAINERID 
        { 
            get 
            {
                return this.pACKAGECONTAINERID; 
            } 
            set 
            {
                this.pACKAGECONTAINERID = value;
                onPropertyChanged("PACKAGECONTAINERID");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PACKAGE_CONTAINER_DESC")]
        public string PACKAGECONTAINERDESC 
        { 
            get 
            {
                return this.pACKAGECONTAINERDESC; 
            } 
            set 
            {
                this.pACKAGECONTAINERDESC = value;
                onPropertyChanged("PACKAGECONTAINERDESC");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 