/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class ShipmentStop : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int stopId;
        private int stopSeqNumber;
        private StopTypeEnum stopType;
        private string name;
        private string address1;
        private string city;
        private string state;
        private int postalCode;
        private string country;
        private string contactName;
        private string contactPhone;
        private string contactFax;
        private string address2;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("StopId")]
        public int StopId 
        { 
            get 
            {
                return this.stopId; 
            } 
            set 
            {
                this.stopId = value;
                onPropertyChanged("StopId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("StopSeqNumber")]
        public int StopSeqNumber 
        { 
            get 
            {
                return this.stopSeqNumber; 
            } 
            set 
            {
                this.stopSeqNumber = value;
                onPropertyChanged("StopSeqNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("StopType", ItemConverterType = typeof(StringValuedEnumConverter))]
        public StopTypeEnum StopType 
        { 
            get 
            {
                return this.stopType; 
            } 
            set 
            {
                this.stopType = value;
                onPropertyChanged("StopType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Address1")]
        public string Address1 
        { 
            get 
            {
                return this.address1; 
            } 
            set 
            {
                this.address1 = value;
                onPropertyChanged("Address1");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("City")]
        public string City 
        { 
            get 
            {
                return this.city; 
            } 
            set 
            {
                this.city = value;
                onPropertyChanged("City");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("State")]
        public string State 
        { 
            get 
            {
                return this.state; 
            } 
            set 
            {
                this.state = value;
                onPropertyChanged("State");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PostalCode")]
        public int PostalCode 
        { 
            get 
            {
                return this.postalCode; 
            } 
            set 
            {
                this.postalCode = value;
                onPropertyChanged("PostalCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Country")]
        public string Country 
        { 
            get 
            {
                return this.country; 
            } 
            set 
            {
                this.country = value;
                onPropertyChanged("Country");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ContactName")]
        public string ContactName 
        { 
            get 
            {
                return this.contactName; 
            } 
            set 
            {
                this.contactName = value;
                onPropertyChanged("ContactName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ContactPhone")]
        public string ContactPhone 
        { 
            get 
            {
                return this.contactPhone; 
            } 
            set 
            {
                this.contactPhone = value;
                onPropertyChanged("ContactPhone");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ContactFax")]
        public string ContactFax 
        { 
            get 
            {
                return this.contactFax; 
            } 
            set 
            {
                this.contactFax = value;
                onPropertyChanged("ContactFax");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Address2")]
        public string Address2 
        { 
            get 
            {
                return this.address2; 
            } 
            set 
            {
                this.address2 = value;
                onPropertyChanged("Address2");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 