/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class Shipment : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string userId;
        private int billToType = 0;
        private string billCompany;
        private string billContact;
        private string billEmail;
        private string billAddress1;
        private string billCity;
        private string billState;
        private string billPostalCode;
        private string billCountry;
        private string billPhone;
        private DateTime readyDate;
        private DateTime readyTime;
        private DateTime closeTime;
        private DateTime dateEntered;
        private bool containsHazmat = false;
        private int serviceType = 0;
        private int chargeType = 0;
        private string comments;
        private DateTime serviceDate;
        private bool tenderEmailOn = true;
        private bool isTendered = false;
        private bool sendConfirm = true;
        private bool attachBol = false;
        private ShipmentStops shipmentStops;
        private ShipmentPieces shipmentPieces;
        private string shipmentId;
        private bool? isDeleted = false;
        private string carrierName;
        private AccCharges accCharges;
        private AccItems accItems;
        private ShipmentReferences shipmentReferences;
        private Printables printables;
        private Errors errors;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("UserId")]
        public string UserId 
        { 
            get 
            {
                return this.userId; 
            } 
            set 
            {
                this.userId = value;
                onPropertyChanged("UserId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillToType")]
        public int BillToType 
        { 
            get 
            {
                return this.billToType; 
            } 
            set 
            {
                this.billToType = value;
                onPropertyChanged("BillToType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillCompany")]
        public string BillCompany 
        { 
            get 
            {
                return this.billCompany; 
            } 
            set 
            {
                this.billCompany = value;
                onPropertyChanged("BillCompany");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillContact")]
        public string BillContact 
        { 
            get 
            {
                return this.billContact; 
            } 
            set 
            {
                this.billContact = value;
                onPropertyChanged("BillContact");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillEmail")]
        public string BillEmail 
        { 
            get 
            {
                return this.billEmail; 
            } 
            set 
            {
                this.billEmail = value;
                onPropertyChanged("BillEmail");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillAddress1")]
        public string BillAddress1 
        { 
            get 
            {
                return this.billAddress1; 
            } 
            set 
            {
                this.billAddress1 = value;
                onPropertyChanged("BillAddress1");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillCity")]
        public string BillCity 
        { 
            get 
            {
                return this.billCity; 
            } 
            set 
            {
                this.billCity = value;
                onPropertyChanged("BillCity");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillState")]
        public string BillState 
        { 
            get 
            {
                return this.billState; 
            } 
            set 
            {
                this.billState = value;
                onPropertyChanged("BillState");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillPostalCode")]
        public string BillPostalCode 
        { 
            get 
            {
                return this.billPostalCode; 
            } 
            set 
            {
                this.billPostalCode = value;
                onPropertyChanged("BillPostalCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillCountry")]
        public string BillCountry 
        { 
            get 
            {
                return this.billCountry; 
            } 
            set 
            {
                this.billCountry = value;
                onPropertyChanged("BillCountry");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BillPhone")]
        public string BillPhone 
        { 
            get 
            {
                return this.billPhone; 
            } 
            set 
            {
                this.billPhone = value;
                onPropertyChanged("BillPhone");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("ReadyDate")]
        public DateTime ReadyDate 
        { 
            get 
            {
                return this.readyDate; 
            } 
            set 
            {
                this.readyDate = value;
                onPropertyChanged("ReadyDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("ReadyTime")]
        public DateTime ReadyTime 
        { 
            get 
            {
                return this.readyTime; 
            } 
            set 
            {
                this.readyTime = value;
                onPropertyChanged("ReadyTime");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("CloseTime")]
        public DateTime CloseTime 
        { 
            get 
            {
                return this.closeTime; 
            } 
            set 
            {
                this.closeTime = value;
                onPropertyChanged("CloseTime");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("DateEntered")]
        public DateTime DateEntered 
        { 
            get 
            {
                return this.dateEntered; 
            } 
            set 
            {
                this.dateEntered = value;
                onPropertyChanged("DateEntered");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ContainsHazmat")]
        public bool ContainsHazmat 
        { 
            get 
            {
                return this.containsHazmat; 
            } 
            set 
            {
                this.containsHazmat = value;
                onPropertyChanged("ContainsHazmat");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ServiceType")]
        public int ServiceType 
        { 
            get 
            {
                return this.serviceType; 
            } 
            set 
            {
                this.serviceType = value;
                onPropertyChanged("ServiceType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ChargeType")]
        public int ChargeType 
        { 
            get 
            {
                return this.chargeType; 
            } 
            set 
            {
                this.chargeType = value;
                onPropertyChanged("ChargeType");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Comments")]
        public string Comments 
        { 
            get 
            {
                return this.comments; 
            } 
            set 
            {
                this.comments = value;
                onPropertyChanged("Comments");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("ServiceDate")]
        public DateTime ServiceDate 
        { 
            get 
            {
                return this.serviceDate; 
            } 
            set 
            {
                this.serviceDate = value;
                onPropertyChanged("ServiceDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TenderEmailOn")]
        public bool TenderEmailOn 
        { 
            get 
            {
                return this.tenderEmailOn; 
            } 
            set 
            {
                this.tenderEmailOn = value;
                onPropertyChanged("TenderEmailOn");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsTendered")]
        public bool IsTendered 
        { 
            get 
            {
                return this.isTendered; 
            } 
            set 
            {
                this.isTendered = value;
                onPropertyChanged("IsTendered");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SendConfirm")]
        public bool SendConfirm 
        { 
            get 
            {
                return this.sendConfirm; 
            } 
            set 
            {
                this.sendConfirm = value;
                onPropertyChanged("SendConfirm");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AttachBol")]
        public bool AttachBol 
        { 
            get 
            {
                return this.attachBol; 
            } 
            set 
            {
                this.attachBol = value;
                onPropertyChanged("AttachBol");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ShipmentStops")]
        public ShipmentStops ShipmentStops 
        { 
            get 
            {
                return this.shipmentStops; 
            } 
            set 
            {
                this.shipmentStops = value;
                onPropertyChanged("ShipmentStops");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ShipmentPieces")]
        public ShipmentPieces ShipmentPieces 
        { 
            get 
            {
                return this.shipmentPieces; 
            } 
            set 
            {
                this.shipmentPieces = value;
                onPropertyChanged("ShipmentPieces");
            }
        }

        /// <summary>
        /// Shipment
        /// </summary>
        [JsonProperty("ShipmentId")]
        public string ShipmentId 
        { 
            get 
            {
                return this.shipmentId; 
            } 
            set 
            {
                this.shipmentId = value;
                onPropertyChanged("ShipmentId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IsDeleted")]
        public bool? IsDeleted 
        { 
            get 
            {
                return this.isDeleted; 
            } 
            private set 
            {
                this.isDeleted = value;
                onPropertyChanged("IsDeleted");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CarrierName")]
        public string CarrierName 
        { 
            get 
            {
                return this.carrierName; 
            } 
            set 
            {
                this.carrierName = value;
                onPropertyChanged("CarrierName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AccCharges")]
        public AccCharges AccCharges 
        { 
            get 
            {
                return this.accCharges; 
            } 
            private set 
            {
                this.accCharges = value;
                onPropertyChanged("AccCharges");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("AccItems")]
        public AccItems AccItems 
        { 
            get 
            {
                return this.accItems; 
            } 
            set 
            {
                this.accItems = value;
                onPropertyChanged("AccItems");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ShipmentReferences")]
        public ShipmentReferences ShipmentReferences 
        { 
            get 
            {
                return this.shipmentReferences; 
            } 
            set 
            {
                this.shipmentReferences = value;
                onPropertyChanged("ShipmentReferences");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Printables")]
        public Printables Printables 
        { 
            get 
            {
                return this.printables; 
            } 
            set 
            {
                this.printables = value;
                onPropertyChanged("Printables");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Errors")]
        public Errors Errors 
        { 
            get 
            {
                return this.errors; 
            } 
            set 
            {
                this.errors = value;
                onPropertyChanged("Errors");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 