/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class SHIPMENT : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string uSERID;
        private int bILLTOTYPE = 0;
        private string bILLCOMPANY;
        private string bILLCONTACT;
        private string bILLEMAIL;
        private string bILLADDRESS1;
        private string bILLCITY;
        private string bILLSTATE;
        private int bILLPOSTALCODE;
        private string bILLCOUNTRY;
        private int bILLPHONE;
        private DateTime rEADYDATE;
        private DateTime rEADYTIME;
        private DateTime cLOSETIME;
        private DateTime dATEENTERED;
        private bool cONTAINSHAZMAT = false;
        private int sERVICETYPE = 0;
        private int cHARGETYPE = 0;
        private string cOMMENTS;
        private DateTime sERVICEDATE;
        private bool tENDEREMAILON = true;
        private bool iSTENDERED = false;
        private bool sENDCONFIRM = true;
        private bool aTTACHBOL = false;
        private SHIPMENTSTOPS sHIPMENTSTOPS;
        private SHIPMENTPIECES sHIPMENTPIECES;
        private string sHIPMENTID;
        private bool? iSDELETED = false;
        private string cARRIERNAME;
        private ACCCHARGES aCCCHARGES;
        private ACCITEMS aCCITEMS;
        private SHIPMENTREFERENCES sHIPMENTREFERENCES;
        private PRINTABLES pRINTABLES;
        private ERRORS eRRORS;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("USER_ID")]
        public string USERID 
        { 
            get 
            {
                return this.uSERID; 
            } 
            set 
            {
                this.uSERID = value;
                onPropertyChanged("USERID");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BILLTOTYPE")]
        public int BILLTOTYPE 
        { 
            get 
            {
                return this.bILLTOTYPE; 
            } 
            set 
            {
                this.bILLTOTYPE = value;
                onPropertyChanged("BILLTOTYPE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BILL_COMPANY")]
        public string BILLCOMPANY 
        { 
            get 
            {
                return this.bILLCOMPANY; 
            } 
            set 
            {
                this.bILLCOMPANY = value;
                onPropertyChanged("BILLCOMPANY");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BILL_CONTACT")]
        public string BILLCONTACT 
        { 
            get 
            {
                return this.bILLCONTACT; 
            } 
            set 
            {
                this.bILLCONTACT = value;
                onPropertyChanged("BILLCONTACT");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BILL_EMAIL")]
        public string BILLEMAIL 
        { 
            get 
            {
                return this.bILLEMAIL; 
            } 
            set 
            {
                this.bILLEMAIL = value;
                onPropertyChanged("BILLEMAIL");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BILL_ADDRESS_1")]
        public string BILLADDRESS1 
        { 
            get 
            {
                return this.bILLADDRESS1; 
            } 
            set 
            {
                this.bILLADDRESS1 = value;
                onPropertyChanged("BILLADDRESS1");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BILL_CITY")]
        public string BILLCITY 
        { 
            get 
            {
                return this.bILLCITY; 
            } 
            set 
            {
                this.bILLCITY = value;
                onPropertyChanged("BILLCITY");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BILL_STATE")]
        public string BILLSTATE 
        { 
            get 
            {
                return this.bILLSTATE; 
            } 
            set 
            {
                this.bILLSTATE = value;
                onPropertyChanged("BILLSTATE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BILL_POSTAL_CODE")]
        public int BILLPOSTALCODE 
        { 
            get 
            {
                return this.bILLPOSTALCODE; 
            } 
            set 
            {
                this.bILLPOSTALCODE = value;
                onPropertyChanged("BILLPOSTALCODE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BILL_COUNTRY")]
        public string BILLCOUNTRY 
        { 
            get 
            {
                return this.bILLCOUNTRY; 
            } 
            set 
            {
                this.bILLCOUNTRY = value;
                onPropertyChanged("BILLCOUNTRY");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("BILL_PHONE")]
        public int BILLPHONE 
        { 
            get 
            {
                return this.bILLPHONE; 
            } 
            set 
            {
                this.bILLPHONE = value;
                onPropertyChanged("BILLPHONE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("READY_DATE")]
        public DateTime READYDATE 
        { 
            get 
            {
                return this.rEADYDATE; 
            } 
            set 
            {
                this.rEADYDATE = value;
                onPropertyChanged("READYDATE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("READY_TIME")]
        public DateTime READYTIME 
        { 
            get 
            {
                return this.rEADYTIME; 
            } 
            set 
            {
                this.rEADYTIME = value;
                onPropertyChanged("READYTIME");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("CLOSE_TIME")]
        public DateTime CLOSETIME 
        { 
            get 
            {
                return this.cLOSETIME; 
            } 
            set 
            {
                this.cLOSETIME = value;
                onPropertyChanged("CLOSETIME");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("DATE_ENTERED")]
        public DateTime DATEENTERED 
        { 
            get 
            {
                return this.dATEENTERED; 
            } 
            set 
            {
                this.dATEENTERED = value;
                onPropertyChanged("DATEENTERED");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CONTAINS_HAZMAT")]
        public bool CONTAINSHAZMAT 
        { 
            get 
            {
                return this.cONTAINSHAZMAT; 
            } 
            set 
            {
                this.cONTAINSHAZMAT = value;
                onPropertyChanged("CONTAINSHAZMAT");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SERVICE_TYPE")]
        public int SERVICETYPE 
        { 
            get 
            {
                return this.sERVICETYPE; 
            } 
            set 
            {
                this.sERVICETYPE = value;
                onPropertyChanged("SERVICETYPE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CHARGE_TYPE")]
        public int CHARGETYPE 
        { 
            get 
            {
                return this.cHARGETYPE; 
            } 
            set 
            {
                this.cHARGETYPE = value;
                onPropertyChanged("CHARGETYPE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("COMMENTS")]
        public string COMMENTS 
        { 
            get 
            {
                return this.cOMMENTS; 
            } 
            set 
            {
                this.cOMMENTS = value;
                onPropertyChanged("COMMENTS");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("SERVICE_DATE")]
        public DateTime SERVICEDATE 
        { 
            get 
            {
                return this.sERVICEDATE; 
            } 
            set 
            {
                this.sERVICEDATE = value;
                onPropertyChanged("SERVICEDATE");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("TENDER_EMAIL_ON")]
        public bool TENDEREMAILON 
        { 
            get 
            {
                return this.tENDEREMAILON; 
            } 
            set 
            {
                this.tENDEREMAILON = value;
                onPropertyChanged("TENDEREMAILON");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("IS_TENDERED")]
        public bool ISTENDERED 
        { 
            get 
            {
                return this.iSTENDERED; 
            } 
            set 
            {
                this.iSTENDERED = value;
                onPropertyChanged("ISTENDERED");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SEND_CONFIRM")]
        public bool SENDCONFIRM 
        { 
            get 
            {
                return this.sENDCONFIRM; 
            } 
            set 
            {
                this.sENDCONFIRM = value;
                onPropertyChanged("SENDCONFIRM");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ATTACH_BOL")]
        public bool ATTACHBOL 
        { 
            get 
            {
                return this.aTTACHBOL; 
            } 
            set 
            {
                this.aTTACHBOL = value;
                onPropertyChanged("ATTACHBOL");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SHIPMENT_STOPS")]
        public SHIPMENTSTOPS SHIPMENTSTOPS 
        { 
            get 
            {
                return this.sHIPMENTSTOPS; 
            } 
            set 
            {
                this.sHIPMENTSTOPS = value;
                onPropertyChanged("SHIPMENTSTOPS");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SHIPMENT_PIECES")]
        public SHIPMENTPIECES SHIPMENTPIECES 
        { 
            get 
            {
                return this.sHIPMENTPIECES; 
            } 
            set 
            {
                this.sHIPMENTPIECES = value;
                onPropertyChanged("SHIPMENTPIECES");
            }
        }

        /// <summary>
        /// Shipment
        /// </summary>
        [JsonProperty("SHIPMENT_ID")]
        public string SHIPMENTID 
        { 
            get 
            {
                return this.sHIPMENTID; 
            } 
            set 
            {
                this.sHIPMENTID = value;
                onPropertyChanged("SHIPMENTID");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ISDELETED")]
        public bool? ISDELETED 
        { 
            get 
            {
                return this.iSDELETED; 
            } 
            private set 
            {
                this.iSDELETED = value;
                onPropertyChanged("ISDELETED");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CARRIER_NAME")]
        public string CARRIERNAME 
        { 
            get 
            {
                return this.cARRIERNAME; 
            } 
            set 
            {
                this.cARRIERNAME = value;
                onPropertyChanged("CARRIERNAME");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ACC_CHARGES")]
        public ACCCHARGES ACCCHARGES 
        { 
            get 
            {
                return this.aCCCHARGES; 
            } 
            private set 
            {
                this.aCCCHARGES = value;
                onPropertyChanged("ACCCHARGES");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ACC_ITEMS")]
        public ACCITEMS ACCITEMS 
        { 
            get 
            {
                return this.aCCITEMS; 
            } 
            set 
            {
                this.aCCITEMS = value;
                onPropertyChanged("ACCITEMS");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("SHIPMENT_REFERENCES")]
        public SHIPMENTREFERENCES SHIPMENTREFERENCES 
        { 
            get 
            {
                return this.sHIPMENTREFERENCES; 
            } 
            set 
            {
                this.sHIPMENTREFERENCES = value;
                onPropertyChanged("SHIPMENTREFERENCES");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PRINTABLES")]
        public PRINTABLES PRINTABLES 
        { 
            get 
            {
                return this.pRINTABLES; 
            } 
            set 
            {
                this.pRINTABLES = value;
                onPropertyChanged("PRINTABLES");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ERRORS")]
        public ERRORS ERRORS 
        { 
            get 
            {
                return this.eRRORS; 
            } 
            set 
            {
                this.eRRORS = value;
                onPropertyChanged("ERRORS");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 