/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum StopTypeEnum
    {
        ORIG, //TODO: Write general description for this method
        DEST, //TODO: Write general description for this method
        STOP, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type StopTypeEnum
    /// </summary>
    public static class StopTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "ORIG", "DEST", "STOP" };

        /// <summary>
        /// Converts a StopTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The StopTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(StopTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case StopTypeEnum.ORIG:
                case StopTypeEnum.DEST:
                case StopTypeEnum.STOP:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of StopTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of StopTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<StopTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into StopTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed StopTypeEnum value</returns>
        public static StopTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type StopTypeEnum", value));

            return (StopTypeEnum) index;
        }
    }
} 