/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class Tracking : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string status;
        private DateTime statusDate;
        private string lastLocation;
        private string carrierScac;
        private string carrierName;
        private DateTime pickupDate;
        private DateTime estPickupDate;
        private DateTime estDeliveredDate;
        private string shipmentId;
        private string signedBy;
        private string carrierPro;
        private string trackingLink;
        private DateTime? deliveredDate;
        private Errors errors;

        /// <summary>
        /// Last Status of Shipment
        /// </summary>
        [JsonProperty("Status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Date of last status update
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("StatusDate")]
        public DateTime StatusDate 
        { 
            get 
            {
                return this.statusDate; 
            } 
            set 
            {
                this.statusDate = value;
                onPropertyChanged("StatusDate");
            }
        }

        /// <summary>
        /// Location of last status update
        /// </summary>
        [JsonProperty("LastLocation")]
        public string LastLocation 
        { 
            get 
            {
                return this.lastLocation; 
            } 
            set 
            {
                this.lastLocation = value;
                onPropertyChanged("LastLocation");
            }
        }

        /// <summary>
        /// SCAC of carrier on shipment
        /// </summary>
        [JsonProperty("CarrierScac")]
        public string CarrierScac 
        { 
            get 
            {
                return this.carrierScac; 
            } 
            set 
            {
                this.carrierScac = value;
                onPropertyChanged("CarrierScac");
            }
        }

        /// <summary>
        /// Name of carrier on shipment
        /// </summary>
        [JsonProperty("CarrierName")]
        public string CarrierName 
        { 
            get 
            {
                return this.carrierName; 
            } 
            set 
            {
                this.carrierName = value;
                onPropertyChanged("CarrierName");
            }
        }

        /// <summary>
        /// Date shipment was picked up
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("PickupDate")]
        public DateTime PickupDate 
        { 
            get 
            {
                return this.pickupDate; 
            } 
            set 
            {
                this.pickupDate = value;
                onPropertyChanged("PickupDate");
            }
        }

        /// <summary>
        /// Date shipment was scheduled to be picked up
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("EstPickupDate")]
        public DateTime EstPickupDate 
        { 
            get 
            {
                return this.estPickupDate; 
            } 
            set 
            {
                this.estPickupDate = value;
                onPropertyChanged("EstPickupDate");
            }
        }

        /// <summary>
        /// Estimated delivery date of shipment
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("EstDeliveredDate")]
        public DateTime EstDeliveredDate 
        { 
            get 
            {
                return this.estDeliveredDate; 
            } 
            set 
            {
                this.estDeliveredDate = value;
                onPropertyChanged("EstDeliveredDate");
            }
        }

        /// <summary>
        /// Shipment Id or BOL number of shipment
        /// </summary>
        [JsonProperty("ShipmentId")]
        public string ShipmentId 
        { 
            get 
            {
                return this.shipmentId; 
            } 
            set 
            {
                this.shipmentId = value;
                onPropertyChanged("ShipmentId");
            }
        }

        /// <summary>
        /// Name of person on Proof of Delivery
        /// </summary>
        [JsonProperty("SignedBy")]
        public string SignedBy 
        { 
            get 
            {
                return this.signedBy; 
            } 
            set 
            {
                this.signedBy = value;
                onPropertyChanged("SignedBy");
            }
        }

        /// <summary>
        /// Pro number of shipment
        /// </summary>
        [JsonProperty("CarrierPro")]
        public string CarrierPro 
        { 
            get 
            {
                return this.carrierPro; 
            } 
            set 
            {
                this.carrierPro = value;
                onPropertyChanged("CarrierPro");
            }
        }

        /// <summary>
        /// Link to track shipment
        /// </summary>
        [JsonProperty("TrackingLink")]
        public string TrackingLink 
        { 
            get 
            {
                return this.trackingLink; 
            } 
            set 
            {
                this.trackingLink = value;
                onPropertyChanged("TrackingLink");
            }
        }

        /// <summary>
        /// Delivery date of shipment
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("DeliveredDate")]
        public DateTime? DeliveredDate 
        { 
            get 
            {
                return this.deliveredDate; 
            } 
            set 
            {
                this.deliveredDate = value;
                onPropertyChanged("DeliveredDate");
            }
        }

        /// <summary>
        /// Any errors from tracking
        /// </summary>
        [JsonProperty("Errors")]
        public Errors Errors 
        { 
            get 
            {
                return this.errors; 
            } 
            set 
            {
                this.errors = value;
                onPropertyChanged("Errors");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 