/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TMSAPI.PCL;
using TMSAPI.PCL.Utilities;

namespace TMSAPI.PCL.Models
{
    public class TRACKING : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string sTATUS;
        private DateTime sTATUSDATE;
        private string lASTLOCATION;
        private string cARRIERSCAC;
        private string cARRIERNAME;
        private DateTime pICKUPDATE;
        private DateTime eSTPICKUPDATE;
        private DateTime eSTDELIVEREDDATE;
        private string sHIPMENTID;
        private string sIGNEDBY;
        private string cARRIERPRO;
        private string tRACKINGLINK;
        private DateTime? dELIVEREDDATE;
        private ERRORS eRRORS;

        /// <summary>
        /// Last Status of Shipment
        /// </summary>
        [JsonProperty("STATUS")]
        public string STATUS 
        { 
            get 
            {
                return this.sTATUS; 
            } 
            set 
            {
                this.sTATUS = value;
                onPropertyChanged("STATUS");
            }
        }

        /// <summary>
        /// Date of last status update
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("STATUS_DATE")]
        public DateTime STATUSDATE 
        { 
            get 
            {
                return this.sTATUSDATE; 
            } 
            set 
            {
                this.sTATUSDATE = value;
                onPropertyChanged("STATUSDATE");
            }
        }

        /// <summary>
        /// Location of last status update
        /// </summary>
        [JsonProperty("LAST_LOCATION")]
        public string LASTLOCATION 
        { 
            get 
            {
                return this.lASTLOCATION; 
            } 
            set 
            {
                this.lASTLOCATION = value;
                onPropertyChanged("LASTLOCATION");
            }
        }

        /// <summary>
        /// SCAC of carrier on shipment
        /// </summary>
        [JsonProperty("CARRIER_SCAC")]
        public string CARRIERSCAC 
        { 
            get 
            {
                return this.cARRIERSCAC; 
            } 
            set 
            {
                this.cARRIERSCAC = value;
                onPropertyChanged("CARRIERSCAC");
            }
        }

        /// <summary>
        /// Name of carrier on shipment
        /// </summary>
        [JsonProperty("CARRIER_NAME")]
        public string CARRIERNAME 
        { 
            get 
            {
                return this.cARRIERNAME; 
            } 
            set 
            {
                this.cARRIERNAME = value;
                onPropertyChanged("CARRIERNAME");
            }
        }

        /// <summary>
        /// Date shipment was picked up
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("PICKUP_DATE")]
        public DateTime PICKUPDATE 
        { 
            get 
            {
                return this.pICKUPDATE; 
            } 
            set 
            {
                this.pICKUPDATE = value;
                onPropertyChanged("PICKUPDATE");
            }
        }

        /// <summary>
        /// Date shipment was scheduled to be picked up
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("EST_PICKUP_DATE")]
        public DateTime ESTPICKUPDATE 
        { 
            get 
            {
                return this.eSTPICKUPDATE; 
            } 
            set 
            {
                this.eSTPICKUPDATE = value;
                onPropertyChanged("ESTPICKUPDATE");
            }
        }

        /// <summary>
        /// Estimated delivery date of shipment
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("EST_DELIVERED_DATE")]
        public DateTime ESTDELIVEREDDATE 
        { 
            get 
            {
                return this.eSTDELIVEREDDATE; 
            } 
            set 
            {
                this.eSTDELIVEREDDATE = value;
                onPropertyChanged("ESTDELIVEREDDATE");
            }
        }

        /// <summary>
        /// Shipment Id or BOL number of shipment
        /// </summary>
        [JsonProperty("SHIPMENT_ID")]
        public string SHIPMENTID 
        { 
            get 
            {
                return this.sHIPMENTID; 
            } 
            set 
            {
                this.sHIPMENTID = value;
                onPropertyChanged("SHIPMENTID");
            }
        }

        /// <summary>
        /// Name of person on Proof of Delivery
        /// </summary>
        [JsonProperty("SIGNED_BY")]
        public string SIGNEDBY 
        { 
            get 
            {
                return this.sIGNEDBY; 
            } 
            set 
            {
                this.sIGNEDBY = value;
                onPropertyChanged("SIGNEDBY");
            }
        }

        /// <summary>
        /// Pro number of shipment
        /// </summary>
        [JsonProperty("CARRIER_PRO")]
        public string CARRIERPRO 
        { 
            get 
            {
                return this.cARRIERPRO; 
            } 
            set 
            {
                this.cARRIERPRO = value;
                onPropertyChanged("CARRIERPRO");
            }
        }

        /// <summary>
        /// Link to track shipment
        /// </summary>
        [JsonProperty("TRACKING_LINK")]
        public string TRACKINGLINK 
        { 
            get 
            {
                return this.tRACKINGLINK; 
            } 
            set 
            {
                this.tRACKINGLINK = value;
                onPropertyChanged("TRACKINGLINK");
            }
        }

        /// <summary>
        /// Delivery date of shipment
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("DELIVERED_DATE")]
        public DateTime? DELIVEREDDATE 
        { 
            get 
            {
                return this.dELIVEREDDATE; 
            } 
            set 
            {
                this.dELIVEREDDATE = value;
                onPropertyChanged("DELIVEREDDATE");
            }
        }

        /// <summary>
        /// Any errors from tracking
        /// </summary>
        [JsonProperty("ERRORS")]
        public ERRORS ERRORS 
        { 
            get 
            {
                return this.eRRORS; 
            } 
            set 
            {
                this.eRRORS = value;
                onPropertyChanged("ERRORS");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 