/*
 * TMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/20/2016
 */
using System;
using TMSAPI.PCL.Controllers;
using TMSAPI.PCL.Http.Client;

namespace TMSAPI.PCL
{
    public partial class TMSAPIClient
    {

        /// <summary>
        /// Singleton access to Other controller
        /// </summary>
        public OtherController Other
        {
            get
            {
                return OtherController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Shipment controller
        /// </summary>
        public ShipmentController Shipment
        {
            get
            {
                return ShipmentController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Quote controller
        /// </summary>
        public QuoteController Quote
        {
            get
            {
                return QuoteController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Order controller
        /// </summary>
        public OrderController Order
        {
            get
            {
                return OrderController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Tracking controller
        /// </summary>
        public TrackingController Tracking
        {
            get
            {
                return TrackingController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public TMSAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public TMSAPIClient(string basicAuthUserName, string basicAuthPassword)
        {
            Configuration.BasicAuthUserName = basicAuthUserName;
            Configuration.BasicAuthPassword = basicAuthPassword;
        }
    }
}